#! /bin/sh

/etc/init.d/dnode

udevd --daemon
udevstart
EnvPartCheck&
mount -t squashfs /dev/mtdblock2 /usr
mount -t squashfs /dev/mtdblock3 /mnt/web
mount -t squashfs /dev/mtdblock4 /mnt/custom
mount -t cramfs /dev/mtdblock5 /mnt/logo
mount -t jffs2 /dev/mtdblock6 /mnt/mtd

mount -t ramfs  /dev/mem        /var
mount -t usbfs none /proc/bus/usb/

#ifconfig eth0 up
#ifconfig eth0 10.6.2.131
mkdir -p /mnt/mtd/Config /mnt/mtd/Log /mnt/mtd/Config/ppp /mnt/mtd/Config/Json

if [ ! -f /mnt/mtd/Config/HvrMode ] && [ -f /mnt/custom/HvrMode ]; then
	cp /mnt/custom/HvrMode /mnt/mtd/Config/
fi
if [ -f /mnt/mtd/Config/ppp/3gdigal ]; then
	chmod 777 /mnt/mtd/Config/ppp/3gdigal
fi
cd /usr/etc
./loadmod
ifconfig eth2 up
ifconfig eth2 10.6.55.55
echo 2548 > /proc/sys/vm/min_free_kbytes

routedaemon&

dogtest &

BurnSataHub &

timecheck &

macGuarder &

#BurnSataHub &
sleep 3
netinit &
sleep 2
#加密芯片scl管脚初始化强制GPIO口模式
himm 0x200f00c0 0x1

/usr/etc/pppd pty /etc/ppp/pppoe-start file /etc/ppp/pppoe-options &

/mnt/custom/extapp.sh &

#unrar x /usr/bin/Sofia.rar /var/
cp /usr/bin/Sofia.tar.lzma /var/
cd /var/
tar -axf /usr/bin/Sofia.tar.lzma

chmod 777 /var/Sofia
rm /var/Sofia.tar.lzma -fr

/etc/extapp.sh &

dvrHelper /lib/modules /usr/sbin/SofiaRun.sh 127.0.0.1 9578 1 &

